# config.yaml (VERSÃO COM RL)
risk:
  risk_per_trade: 0.02
  max_daily_trades: 10
  daily_loss_limit: -100
  cooldown_period: 30
  max_position_value: 50
  min_position_value: 20
  rl_enabled: true          # NOVO: Ativa Reinforcement Learning

trading:
  enabled_pairs:
    - "BTC/USDT"
    - "ETH/USDT"
    - "ADA/USDT"
  strategy: "hybrid_rl"     # NOVO: Estratégia híbrida
  analysis_interval: 60
  max_open_positions: 3

exchange:
  name: "binance"
  api_key: "test_key"
  secret: "test_secret"
  sandbox: true
  order_timeout: 30

logging:
  level: "INFO"
  file: "trading_bot.log"

rl_settings:                # NOVA SEÇÃO
  state_size: 10
  enable_training: true
  model_save_interval: 1000
